### ISSUE TITLE
LSP & LSR tests synchronization timeout fail

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1250]
**Some time LSP & LSR test fail with the following stack trace:**

 Test method TypeCobol.LanguageServer.Test.LSRTest.VariableQualifiedNameCompletion2 threw exception: 
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\projects\typecobol\bin\EI_Debug\LSRTests\VariableQualifiedNameCompletion2\input\Results'.
Stack Trace:
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   at CLI.Test.UnitTestHelper.CompareDirectory(DirectoryInfo targetDir, DirectoryInfo actualDir, String testPlaylistDirectory) in C:\projects\typecobol\CLI\test\CLITest.cs:line 348
   at TypeCobol.LanguageServer.Test.LSRTestHelper.Test(String testFolderName, LsrTestingOptions lsrTestingOption, Boolean activateTdOption, String copyFolder, String customIntrinsicFile, String customDependenciesFolder) in C:\projects\typecobol\TypeCobol.LanguageServer.Test\LSRTestHelper.cs:line 92
   at TypeCobol.LanguageServer.Test.LSRTest.VariableQualifiedNameCompletion2() in C:\projects\typecobol\TypeCobol.LanguageServer.Test\LSRTest.cs:line 181

**Comment by maxime645** [comment]
[TCLSPLog.txt](https://github.com/TypeCobolTeam/TypeCobol/files/2816614/TCLSPLog.txt)
[LSRLog.txt](https://github.com/TypeCobolTeam/TypeCobol/files/2816615/LSRLog.txt)

Here are the logs taken from the Appveyor VM for environment Debug
