### ISSUE TITLE
Codegen : Call procedure pointer causes exception

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1515]
**Describe the bug**
Bug when you generate the following code:

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       LINKAGE SECTION.
       01  PP                            PROCEDURE-POINTER.
      
       PROCEDURE DIVISION.
           CALL PP
           GOBACK
           .
       END PROGRAM MyPGM.
      
```
The line which cause the problem is `CALL PP`
Exception
```
   at TypeCobol.Server.CLI.runOnce2(TypeCobolConfiguration config, AbstractErrorWriter errorWriter)
   at TypeCobol.Server.CLI.runOnce(TypeCobolConfiguration config)


   at TypeCobol.Codegen.Nodes.ProcedureStyleCall.get_Lines()
   at TypeCobol.Codegen.Generators.DefaultGenerator.d__40.MoveNext()
   at TypeCobol.Codegen.Generators.DefaultGenerator.LinearGeneration[A](LinearNodeSourceCodeMapper mapper, LinearNodeSourceCodeMapper clonedMapper, IReadOnlyList`1 Input, LineMappingCtx lmCtx, Int32 startLine, Int32 endLine)
   at TypeCobol.Codegen.Generators.DefaultGeneratorWithLineMap.LinearGeneration[A](LinearNodeSourceCodeMapper mapper, IReadOnlyList`1 Input, LinearNodeSourceCodeMapper clonedMapper)
   at TypeCobol.Codegen.Generators.DefaultGenerator.TreeToCode()
   at TypeCobol.Codegen.Generators.MixedTransformGenerator.Generate(CompilationUnit compilationUnit, ColumnsLayout columns)
   at TypeCobol.Server.CLI.runOnce2(TypeCobolConfiguration config, AbstractErrorWriter errorWriter)

```

**Expected behavior**
No exception.

**Comment by fm-117** [comment]
The call is mistakenly parsed as a Procedure call (TC-specific) instead of a regular COBOL procedure-pointer call. After that, Codegen will try to generate code for the call but will fail as there is no FunctionDeclaration.

It looks like there is an ambiguity in ANTLR grammar for this kind of CALL

```
cobolCallStatement:
	CALL programNameOrProgramEntryOrProcedurePointerOrFunctionPointerVariable
		(USING callUsingParameters+)?
		(RETURNING callReturningParameter)?;
```

vs

```
tcCallStatement:
	CALL procedurePointerOrFunctionPointerVariableOrfunctionNameReference=identifier?
		(INPUT  callInputParameter+)?
		(IN_OUT  callInoutParameter+)?
		(OUTPUT callOutputParameter+)?
```

How to distinguish between the two forms when neither `INPUT` nor `USING` keywords are present ?

**Comment by fm-117** [comment]
Creating replacement code element and node is not a viable solution because code elements are stored initially in an immutable snapshot.

Another solution consists in merging `Call` and `ProcedureStyleCall` in a single class and adapt behavior after determining if it is a standard call or a TC call.

**Comment by smedilol** [comment]
I think this bug is unlikey to happen with production code.
I postpone, this issue.
