### ISSUE TITLE
CodeElement.get_Column out of range

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#204]
Since #196, parsing of sample file `IPCTPPRT.PGM` fails with a `System.ArgumentOutOfRangeException` thrown in `CodeElement.get_Column`.
`CodeElement.ConsumedTokens` must be `null` or empty ...

**Comment by wiztigers** [comment]
I confirm this error wasn't present before meging the PR #196.

To assert this, one can checkout revision d9971b1f0f169970706f728a5d57680ca2f2f49c and run the sample parsing after applying the following patch (to remove another error in `MoveStatement.cs` that was fixed in 16864b9efdacef7e03fc6be459e3c3c3369669e5) :
```git
diff --git a/TypeCobol/Compiler/CodeElements/Statement/MoveStatement.cs b/TypeCobol/Compiler/CodeElements/Statement/MoveStatement.cs
index 5903fa7..62cc610 100644
--- a/TypeCobol/Compiler/CodeElements/Statement/MoveStatement.cs
+++ b/TypeCobol/Compiler/CodeElements/Statement/MoveStatement.cs
@@ -53,13 +53,21 @@ namespace TypeCobol.Compiler.CodeElements
         public Dictionary<QualifiedName,bool> Symbols {
             get {
                 var symbols = new Dictionary<QualifiedName,bool>();
-                if (Sending is Identifier)
-                    symbols.Add(((Identifier)Sending).Name, false);
-                foreach (var identifier in Receiving)
-                    symbols.Add(identifier.Name, true);
+                               var name = asUserDefinedName(Sending);
+                               if (name != null) symbols.Add(name, false);
+                foreach (var identifier in Receiving) {
+                                       name = asUserDefinedName(identifier);
+                                       if (name != null) symbols.Add(name, false);
+                               }
                 return symbols;
             }
             private set { throw new System.InvalidOperationException(); }
         }
+               private QualifiedName asUserDefinedName(Expression expression) {
+                       if (!(expression is Identifier)) return null;
+                       if (expression is SpecialRegister) return null;
+                       if (expression is FunctionReference) return null;
+                       return ((Identifier)expression).Name;
+               }
     }
 }

```

**Comment by wiztigers** [comment]
@laurentprudhon, thanks in advance for your analysis.
I can fix this later, but I've must address some other tickets before.

**Comment by wiztigers** [comment]
I confirm that `IPCTPPRT.PGM` is the only file in error in our production sample.

Analysis is made more difficult by the fact that the error happens in library code calling generated code.
Here is the stacktrace :
```
Test Name:	CheckGrammarCorrectness
Test FullName:	TypeCobol.Test.GrammarTest.CheckGrammarCorrectness
Test Source:	c:\code\TypeCobol\TypeCobol.Test\GrammarTest.cs : line 16
Test Outcome:	Failed
Test Duration:	0:00:04,2746917

Result Message:	
Test method TypeCobol.Test.GrammarTest.CheckGrammarCorrectness threw exception: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Result StackTrace:	
at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TypeCobol.Compiler.CodeElements.CodeElement.get_Column() in c:\code\TypeCobol\TypeCobol\Compiler\CodeElements\CodeElement.cs:line 109
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at TypeCobol.Compiler.Parser.Generated.CobolProgramClassParser.section() in c:\code\TypeCobol\TypeCobol.Grammar\obj\Debug\CobolProgramClassParser.cs:line 1749
   at TypeCobol.Compiler.Parser.Generated.CobolProgramClassParser.procedureDivision() in c:\code\TypeCobol\TypeCobol.Grammar\obj\Debug\CobolProgramClassParser.cs:line 572
   at TypeCobol.Compiler.Parser.Generated.CobolProgramClassParser.cobolProgram() in c:\code\TypeCobol\TypeCobol.Grammar\obj\Debug\CobolProgramClassParser.cs:line 324
   at TypeCobol.Compiler.Parser.Generated.CobolProgramClassParser.cobolCompilationUnit() in c:\code\TypeCobol\TypeCobol.Grammar\obj\Debug\CobolProgramClassParser.cs:line 231
   at TypeCobol.Compiler.Parser.ProgramClassParserStep.ParseProgramOrClass(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 codeElementsLines, TypeCobolOptions compilerOptions, SymbolTable customSymbols, Program& newProgram, Class& newClass, IList`1& diagnostics) in c:\code\TypeCobol\TypeCobol\Compiler\Parser\ProgramClassParserStep.cs:line 40
   at TypeCobol.Compiler.CompilationUnit.RefreshProgramClassDocumentSnapshot() in c:\code\TypeCobol\TypeCobol\Compiler\CompilationUnit.cs:line 149
   at TypeCobol.Compiler.FileCompiler.CompileOnce() in c:\code\TypeCobol\TypeCobol\Compiler\FileCompiler.cs:line 159
   at TypeCobol.Test.Compiler.Parser.ParserUtils.ParseCobolFile(String textName, DocumentFormat documentFormat, String folder) in c:\code\TypeCobol\TypeCobol.Test\Compiler\Parser\ParserUtils.cs:line 54
   at TypeCobol.Test.GrammarTest.CheckGrammarCorrectness() in c:\code\TypeCobol\TypeCobol.Test\GrammarTest.cs:line 45
```
Any ideas on how to tackle this (•ิヘ•ิ)?

**Comment by wiztigers** [comment]
In some cases, `CodeElement.ConsumedTokens` is *null*.

In **CodeElementsParserStep**:
```csharp
// Try to parse a code element starting with the current token
CodeElementsParser.CodeElementContext codeElementParseTree = cobolParser.codeElement();

// If the parse tree is not empty
if (codeElementParseTree.Start.Type > 0)
{

…

walker.Walk(codeElementBuilder, codeElementParseTree);
CodeElement codeElement = codeElementBuilder.CodeElement;
if (codeElement != null)
{
   // Attach consumed tokens and main document line numbers information to the code element
   codeElement.ConsumedTokens = cobolParser.ConsumedTokens;

   // Add code element to the list                    
   codeElementsLine.AddCodeElement(codeElement);
```

If `ConsumedTokens == null` in the next step, it means we have some error cases in **TracingCobolParser**:
* parse tree is not empty
* `cobolParser.ConsumedTokens = null`

ConsumedTokens is assigned when overriding the following method:
```csharp
public override IToken Consume()
```

In means Antlr can recognize a grammar rule (syntax tree is not empty) without calling `Consume()` with no `Token`.
We do indeed find this pattern in Antlr generated code :
* `RuleContext` created, rule entry listener called
* test first token type
* on unexpected token type: exit rule on error with no call to `Consume()`
It is correct, because maybe there is just one token missing in the program, and we want to keep the token as the next rule first word.

```csharp
public SectionContext section() {
             SectionContext _localctx = new SectionContext(_ctx, State);
             EnterRule(_localctx, 32, RULE_section);
             int _la;
             try {
                    int _alt;
...
                           _la = _input.La(1);
                           if ( !(_la==SectionHeader || _la==ParagraphHeader) ) {
                                 errHandler.RecoverInline(this);
                           } else {
                                  Consume();
                           }
```

**Comment by wiztigers** [comment]
Fix proposed by @prudholu:
* shield agains `ConsumedTokens == null` in class `CodeElement`
* if not at end of file, add the next token to `ConsumedTokens` so we know where is the CodeElement in error
This alter `CodeElements` semantics: in addition to matched tokens, it includes the first token in error if no token has been matched.
