### ISSUE TITLE
FormatException in IntegerLiteralTokenValue constructor

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2387]
**Describe the bug**
A `FormatException` has been thrown in `IntegerLiteralTokenValue` constructor while attempting to parse the integer value.

**To Reproduce**
TODO
No source code to reproduce.

**Expected behavior**
No exception but a diagnostic. Theoretically, this kind of error should be picked up by scanner. We have to ensure no invalid value is created to avoid such exceptions.

**Technical**
Check how the literal is built. If scanner finds an invalid literal either create a distinct LiteralTokenValue or simply skip the literal creation. Check other literal token values creation if they involve calling `Parse` methods from framework.

**How to test automatically**
Standard test using appropriate source code to reproduce the bug.

**Comment by fm-117** [comment]
Stacktrace:

```
at System.Numerics.BigNumber.ParseBigInteger(String value, NumberStyles style, NumberFormatInfo info)
at TypeCobol.Compiler.Scanner.IntegerLiteralTokenValue..ctor(String sign, String number)
at TypeCobol.Compiler.Scanner.AbstractScanner.ScanNumericLiteral(Int32 startIndex, Char decimalPoint)
at TypeCobol.Compiler.Scanner.Scanner.ScanCobolNumericLiteral(Int32 startIndex)
at TypeCobol.Compiler.Scanner.Scanner.ScanOneCharFollowedBySpaceOrNumericLiteral(Int32 startIndex, TokenType tokenType, MessageCode messageCode, Boolean spaceAfterIsMandatory)
at TypeCobol.Compiler.Scanner.Scanner.GetTokenStartingFrom(Int32 startIndex)
at TypeCobol.Compiler.Scanner.AbstractScanner.ScanWhitespace(Int32 startIndex)
at TypeCobol.Compiler.Scanner.Scanner.GetTokenStartingFrom(Int32 startIndex)
at TypeCobol.Compiler.Scanner.Scanner.ScanTokensLine(TokensLine tokensLine, MultilineScanState initialScanState, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, BitArray multiStringConcatBitPosition)
at TypeCobol.Compiler.Scanner.ScannerStep.ScanTokensLineWithContinuations(Int32 lineToScanIndex, TokensLine lineToScan, TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, IList`1 tokensLinesChanges, MultilineScanState scanState, Int32& nextLineToScanIndex, TokensLine& nextLineToScan)
at TypeCobol.Compiler.Scanner.ScannerStep.ScanTokensLineWithMultilineScanState(Int32 lineToScanIndex, TokensLine lineToScan, TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, IList`1 tokensLinesChanges, MultilineScanState scanState, Int32& nextLineToScanIndex, TokensLine& nextLineToScan)
at TypeCobol.Compiler.Scanner.ScannerStep.ScanTextLinesChanges(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, IList`1 textLinesChanges, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, MultilineScanState scanState)
at TypeCobol.Compiler.CompilationDocument.UpdateTokensLines(Action onVersion)
at TypeCobol.Compiler.FileCompiler.CompileOnce(Nullable`1 exec2Step, Boolean haltOnMissingCopy)
at TypeCobol.LanguageServer.Workspace.UpdateSourceFile(Uri fileUri, TextChangedEvent textChangedEvent)
at TypeCobol.LanguageServer.TypeCobolServer.OnDidChangeTextDocument(DidChangeTextDocumentParams parameters)
at TypeCobol.LanguageServer.VsCodeProtocol.LanguageServer.CallDidChangeTextDocument(NotificationType notificationType, Object parameters)
```

**Comment by fm-117** [comment]
This can be reproduced with this code:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID.  Pgm.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC S9V99 VALUE +..
       PROCEDURE DIVISION.
           GOBACK
           .
       END PROGRAM Pgm.
```

I think we should add more controls over the result of the regex. Current code is

https://github.com/TypeCobolTeam/TypeCobol/blob/00daee94f7a65d1dfdc37822d5cf0fac2979e5d0/TypeCobol/Compiler/Scanner/AbstractScanner.cs#L175-L184

with the regex applied being:

```csharp
private static readonly Regex _DecimalLiteralRegex = new Regex("([-+]?)([0-9]*)(?:[\\.,]([0-9]+))?", RegexOptions.Compiled);
```

Regex seems fine however when no decimal part is found, the integral part cannot be empty so I suggest to rewrite this part as

```csharp
if (decMatch.Groups[3].Value.Length > 0)
{
    [...] // Create decimal literal
}
else if (decMatch.Groups[2].Value.Length > 0)
{
    [...] // Create integer literal
}
else
{
    [...] // Error
}
```

@smedilol, do you agree ?
