### ISSUE TITLE
NullReferenceException in Scanner.GetTokenStartingFrom

### ISSUE THREAD

**Issue by efr15** [TypeCobolTeam/TypeCobol#2573]
**Describe the bug**
A `NullReferenceException` occurred in method `GetTokenStartingFrom`.

Stacktrace is:

```
   à TypeCobol.Compiler.Scanner.Scanner.GetTokenStartingFrom(Int32 startIndex)
    à TypeCobol.Compiler.Scanner.Scanner.ScanTokensLine(TokensLine tokensLine, MultilineScanState initialScanState, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, BitArray multiStringConcatBitPosition)
    à TypeCobol.Compiler.Scanner.Scanner.ScanTokensLineContinuationGroup(IList`1 continuationLinesGroup, MultilineScanState initialScanState, ColumnsLayout format, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations)
    à TypeCobol.Compiler.Scanner.ScannerStep.ScanTokensLineWithContinuations(Int32 lineToScanIndex, TokensLine lineToScan, TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, IList`1 tokensLinesChanges, MultilineScanState scanState, Int32& nextLineToScanIndex, TokensLine& nextLineToScan)
    à TypeCobol.Compiler.Scanner.ScannerStep.ScanTokensLineWithMultilineScanState(Int32 lineToScanIndex, TokensLine lineToScan, TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, IList`1 tokensLinesChanges, MultilineScanState scanState, Int32& nextLineToScanIndex, TokensLine& nextLineToScan)
    à TypeCobol.Compiler.Scanner.ScannerStep.ScanTextLinesChanges(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, IList`1 textLinesChanges, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, MultilineScanState scanState)
    à TypeCobol.Compiler.CompilationDocument.UpdateTokensLines(Action onVersion)
    à TypeCobol.Compiler.FileCompiler.CompileOnce(Nullable`1 exec2Step, Boolean haltOnMissingCopy)
    à TypeCobol.LanguageServer.Workspace.UpdateSourceFile(Uri fileUri, RangeUpdate[] updates)
    à TypeCobol.LanguageServer.TypeCobolServer.OnDidChangeTextDocument(DidChangeTextDocumentParams parameters)
    à TypeCobol.LanguageServer.VsCodeProtocol.LanguageServer.CallDidChangeTextDocument(NotificationType notificationType, Object parameters, LSPProfiling lspProfiling)
```

parser version: v1.6.5.

**To Reproduce**
TODO

**Expected behavior**
No exception.

**Technical**
TODO

**How to test automatically**
Standard test

**Comment by fm-117** [comment]
Similar problem occurred but directly in `ScanTokensLine` method (maybe because of .NET 8 inlining ?). Stack trace is:

```
   at TypeCobol.Compiler.Scanner.Scanner.ScanTokensLine(TokensLine tokensLine, MultilineScanState initialScanState, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, BitArray multiStringConcatBitPosition)
   at TypeCobol.Compiler.Scanner.Scanner.ScanTokensLineContinuationGroup(IList`1 continuationLinesGroup, MultilineScanState initialScanState, ColumnsLayout format, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations)
   at TypeCobol.Compiler.Scanner.ScannerStep.ScanTokensLineWithContinuations(Int32 lineToScanIndex, TokensLine lineToScan, TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, IList`1 tokensLinesChanges, MultilineScanState scanState, Int32& nextLineToScanIndex, TokensLine& nextLineToScan)
   at TypeCobol.Compiler.Scanner.ScannerStep.ScanTextLinesChanges(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, IList`1 textLinesChanges, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, List`1 copyTextNameVariations, MultilineScanState scanState)
   at TypeCobol.Compiler.CompilationDocument.UpdateTokensLines(Action onVersion)
   at TypeCobol.Compiler.FileCompiler.CompileOnce(Nullable`1 exec2Step, Boolean haltOnMissingCopy)
   at TypeCobol.LanguageServer.Workspace.UpdateSourceFile(Uri fileUri, RangeUpdate[] updates)
   at TypeCobol.LanguageServer.TypeCobolServer.OnDidChangeTextDocument(DidChangeTextDocumentParams parameters)
   at TypeCobol.LanguageServer.VsCodeProtocol.LanguageServer.CallDidChangeTextDocument(NotificationType notificationType, Object parameters, LSPProfiling lspProfiling)
```
