### ISSUE TITLE
IndexOutOfRangeException in Token.SourceText property

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2599]
**Describe the bug**
The `SourceText` property of `Token` object may throw an `IndexOutOfRangeExcepiton` with the message `startIndex cannot be larger than length of string. (Parameter 'startIndex')`.

**To Reproduce**
No source code to reproduce, it may be related to incremental change.

**Expected behavior**
No exception, such property should be safe to call in any context.

**Technical**
See https://github.com/TypeCobolTeam/TypeCobol/blob/c1fdd30b2ef12a68a93d2e5ea205dd19212702fd/TypeCobol/Compiler/Text/TextLineSnapshot.cs#L36
This `Substring` call is not safe apparently...

**How to test automatically**
Standard tests depending on the source code used to reproduce the bug.

**Comment by fm-117** [comment]
Full stacktrace:

```
   at System.String.Substring(Int32 startIndex, Int32 length)
   at TypeCobol.Compiler.Diagnostics.CodeElementWithTokensChecker.<CheckAreaOfDeclaration>g__CheckToken|1_1(Token token, TextAreaType expectedTextAreaType, <>c__DisplayClass1_0& )
   at TypeCobol.Compiler.Diagnostics.CodeElementWithTokensChecker.CheckAreaOfDeclaration(CodeElement codeElement)
   at TypeCobol.Compiler.Parser.CodeElementsParserStep.ParseProcessedTokensLinesChanges(ProcessedTokensDocument processedTokensDocument, IList`1 processedTokensLinesChanges, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, PerfStatsForParserInvocation perfStatsForParserInvocation)
   at TypeCobol.Compiler.CompilationUnit.RefreshCodeElementsDocumentSnapshot()
   at TypeCobol.Compiler.FileCompiler.CompileOnce(Nullable`1 exec2Step, Boolean haltOnMissingCopy)
   at TypeCobol.LanguageServer.Workspace.UpdateSourceFile(Uri fileUri, RangeUpdate[] updates)
   at TypeCobol.LanguageServer.TypeCobolServer.OnDidChangeTextDocument(DidChangeTextDocumentParams parameters)
   at TypeCobol.LanguageServer.VsCodeProtocol.LanguageServer.CallDidChangeTextDocument(NotificationType notificationType, Object parameters, LSPProfiling lspProfiling)
```

**Comment by fm-117** [comment]
To add a custom trace to help debugging:

```csharp
                    string tokenSourceText;
                    try
                    {
                        tokenSourceText = token.SourceText;
                    }
                    catch
                    {
                        var contextData = new Dictionary<string, object>()
                        {
                            { "TokenType", token.TokenType },
                            { "TokensLine", token.TokensLine.Text },
                            { "StartIndex", token.StartIndex },
                            { "StopIndex", token.StopIndex }
                        };
                        LoggingSystem.LogMessage(LogLevel.Error, "Unable to read SourceText from token", contextData);
                        tokenSourceText = token.TokenType.ToString();
                    }

                    DiagnosticUtils.AddError(codeElement, $"{tokenSourceText} should begin in '{expectedTextAreaType}'. It was found in '{actualStartingArea}'.");
```
