### ISSUE TITLE
NullReferenceException in Workspace.CollectDataLayoutNodes

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2600]
**Describe the bug**
A `NullReferenceException` may be thrown by `Workspace.CollectDataLayoutNodes` method.

**To Reproduce**
No source code to reproduce.

**Expected behavior**
No exception.

**Technical**
See
https://github.com/TypeCobolTeam/TypeCobol/blob/c1fdd30b2ef12a68a93d2e5ea205dd19212702fd/TypeCobol.LanguageServer/Workspace.cs#L1103
This line should be protected against null values.

**How to test automatically**
TODO

**Comment by fm-117** [comment]
Full stacktrace:
```
   at TypeCobol.LanguageServer.Workspace.CollectDataLayoutNodes(CompilationUnit compilationUnit)
   at TypeCobol.LanguageServer.Workspace.GetDataLayoutAsCSV(CompilationUnit compilationUnit, String separator)
   at TypeCobol.LanguageServer.TypeCobolCustomLanguageServerProtocol.TypeCobolCustomLanguageServer.OnDidReceiveGetDataLayout(GetDataLayoutParams parameter)
   at TypeCobol.LanguageServer.TypeCobolCustomLanguageServerProtocol.TypeCobolCustomLanguageServer.ReceivedGetDataLayoutRequest(RequestType requestType, Object parameters, LSPProfiling lspProfiling)
```
