### ISSUE TITLE
QualifiedName :: null reference exception with occurs

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#671]
```COBOL
01  var.
  05 var2.
     10 var3 PIC OCCURS. 
```
When typing `var::var2::` give the following exception :

La référence d'objet n'est pas définie à une instance d'un objet.
   at TypeCobol.Parser.Parse(String path, TextChangedEvent e)
   at TypeCobol.Server.CLI.runOnce2(TypeCobolConfiguration config, AbstractErrorWriter errorWriter)
   at TypeCobol.Server.CLI.runOnce(TypeCobolConfiguration config)
   at TypeCobol.Compiler.Diagnostics.Cobol85CompleteASTChecker.CheckVariable(Node node, StorageArea storageArea)
   at TypeCobol.Compiler.Diagnostics.Cobol85CompleteASTChecker.BeginNode(Node node)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   at TypeCobol.Compiler.Parser.ProgramClassParserStep.ParseProgramOrClass(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 codeElementsLines, TypeCobolOptions compilerOptions, SymbolTable customSymbols, PerfStatsForParserInvocation perfStatsForParserInvocation, SourceFile&amp; root, IList`1&amp; diagnostics, Dictionary`2&amp; nodeCodeElementLinkers)
   at TypeCobol.Compiler.CompilationUnit.RefreshProgramClassDocumentSnapshot()
   at TypeCobol.Compiler.FileCompiler.CompileOnce()
   at TypeCobol.Parser.Parse(String path, TextChangedEvent e)

**Comment by collarbe** [comment]
Not able to reproduce the case... 
I'm closing this issue for now.
