### ISSUE TITLE
Crash of the CodeGenerator with a null reference exception

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#751]
The following stack trace is generated by the code generator.

Code : GenerationFailled - Message : La référence d'objet n'est pas définie à une instance d'un objet.
   at TypeCobol.Server.CLI.runOnce2(TypeCobolConfiguration config, AbstractErrorWriter errorWriter)
   at TypeCobol.Server.CLI.runOnce(TypeCobolConfiguration config)

   at TypeCobol.Codegen.Nodes.TypedDataNode.InsertChildren(Nullable`1 layout, SymbolTable table, List`1 rootVariableName, DataDefinition ownerDefinition, DataDefinition type, Int32 level, Int32 indent)
   at TypeCobol.Codegen.Nodes.TypedDataNode.get_Lines()
   at TypeCobol.Codegen.Generators.DefaultGenerator.NodeLines(Node node)
   at TypeCobol.Codegen.Generators.DefaultGenerator.<NodeLines>d__13.MoveNext()
   at TypeCobol.Codegen.Generators.DefaultGenerator.LinearGeneration[A](LinearNodeSourceCodeMapper mapper, IReadOnlyList`1 Input)
   at TypeCobol.Codegen.Generators.DefaultGenerator.TreeToCode()
   at TypeCobol.Codegen.Generator.Generate(CompilationUnit compilationUnit, ColumnsLayout columns)
   at TypeCobol.Server.CLI.runOnce2(TypeCobolConfiguration config, AbstractErrorWriter errorWriter)

**Comment by mayanje** [comment]
This kind of definition makes the Code Genearor crash.

       01 LoopControl typedef strict private.
         05 loop          pic S9(5) COMP-5.
         05 sta           type bool.
         05 t             type Traceback.
         05 savedTrace    type TraceBack.
       01 control  type LoopControl.

**Comment by mayanje** [comment]
This is related with the declaration of the variable sta with a type bool. The razor Template engine insert a GenerateNode as substitution here which is not expected by the code generator. We must review that.
